sonar.projectKey=Jigar-Parmar13_TeamNotes
sonar.organization=jigar-parmar13-1
sonar.projectName=TeamNotes

sonar.sources=backend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.coverage.exclusions=frontend/**

sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=false