sonar.projectKey=Jigar-Parmar13_TeamNotes
sonar.organization=jigar-parmar13-1
sonar.projectName=TeamNotes

sonar.sources=backend/src
sonar.tests=backend/tests
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,frontend/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.coverage.exclusions=frontend/**,backend/tests/**,**/server.js

sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=false