name: CI Pipeline — TeamNotes

on:
  push:
    branches: [ main, devops ]
  pull_request:
    branches: [ main, devops ]

jobs:

  # ── JOB 1: SonarQube ──────────────────────────
  sonarqube-scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

  # ── JOB 2: Docker Build + Trivy ───────────────
  docker-build-scan:
    name: Docker Build and Trivy Scan
    runs-on: ubuntu-latest
    needs: sonarqube-scan
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Backend Image
        run: docker build -t teamnotes-backend ./backend

      - name: Build Frontend Image
        run: docker build -t teamnotes-frontend ./frontend

      - name: Trivy Scan — Backend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: teamnotes-backend
          format: table
          severity: CRITICAL,HIGH
          exit-code: '0'

      - name: Trivy Scan — Frontend
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: teamnotes-frontend
          format: table
          severity: CRITICAL,HIGH
          exit-code: '0'

  # ── JOB 3: Push to DockerHub ──────────────────
  docker-push:
    name: Push to DockerHub
    runs-on: ubuntu-latest
    needs: docker-build-scan
    if: github.event_name == 'push'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/teamnotes-backend:latest ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/teamnotes-backend:latest

      - name: Build and Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/teamnotes-frontend:latest ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/teamnotes-frontend:latest